/* Generated by es6-transpiler v 0.7.14-2 */
"use strict";

var Scheduled = (function(){var DP$0 = Object.defineProperty;

  function Scheduled(parent) {
    this.parent = parent;
    // written by scheduler only others read
    this.scheduler = null;
  }Object.defineProperties(Scheduled.prototype, {time: {"get": time$get$0, "configurable": true, "enumerable": true}});DP$0(Scheduled, "prototype", {"configurable": false, "enumerable": false, "writable": false});

  // to be implemented by instance
  Scheduled.prototype.reset = function(time) {
    return Infinity;
  }

  // to be implemented by instance
  Scheduled.prototype.execute = function(time) {
    return Infinity;
  }

  Scheduled.prototype.reschedule = function(time) {
    this.scheduler.reschedule(this, time);
  }

  function time$get$0() {
    return this.scheduler.time;
  }
;return Scheduled;})();

module.exports = Scheduled;